server:
  port: 8088
  servlet:
      session:
        timeout: 30m


spring:
  datasource:
    url: jdbc:h2:file:./data/ruqsatdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
	driver-class-name: org.h2.Driver
	username: sa
	password: ""
  jpa:
    hibernate:
      ddl-auto: update
	  dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  main:
    banner-mode: "off"

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG