server:
  port: 8088
  servlet:
      session:
        timeout: 30m


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zkteco
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG